server:
  port: 8766

spring:
  application:
    name: zuul-server

eureka:
  instance:
    instance-id: zuul-server
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    ribbon-route:
      path: /consumer-ribbon/**
      serviceId: consumer-ribbon
    feign-route:
      path: /consumer-feign/**
      serviceId: consumer-feign
    service-provider-route:
      path: /service-provider/**
      serviceId: service-provider