server:
  port: 8762

spring:
  application:
    name: service-provider

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank
    username: gaojc
    password: gaojc
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  #  mapper-locations: classpath:/com/project/mapper/xml/*Mapper.xml #在src/main/java下的写法(同时配置POM文件中source属性)
  mapper-locations: classpath:/com/gaojc/serviceprovider/mapper/impl/*.xml #在resource目录下的写法
  typeAliasesPackage: com.gaojc.serviceprovider.entity #实体扫描，多个package用逗号或者分号分隔
  #  typeEnumsPackage: com.baomidou.springboot.entity.enums #枚举字段扫描，支持实体的枚举字段（看官网Spring Boot实例）
  global-config:
    db-config:
      db-type: MYSQL #数据库类型
      column-underline: true #生成的SQL语句中，字段是否自动加入下划线
    refresh: true #启动后，修改Target中的XML即可马上更新，用于调试；生产中不要启动
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
