server:
  port: 8001

spring:
  application:
    name: provider-security-jwt

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath:com/gaojc/security/mapper/impl/*.xml
  typeAliasesPackage: com.gaojc.security.entity
  global-config:
    id-type: 3
    field-strategy: 2
    #生成的SQL语句中，字段是否自动加入下划线
    db-column-underline: true
    #启动后，修改Target中的XML即可马上更新，用于调试；生产中不要启动
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'

logging:
  level:
    com.baomidou.mybatisplus: debug

jwtTokenSecret: gaojc
tokenExpiredMs: 604800000